import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer'

import { DIMENSION_META, formatCostRange, formatEffort } from '../../lib/format'
import type { AdaptationPlan } from '../../lib/types'

interface PlanPdfProps {
  readonly plan: AdaptationPlan
}

/**
 * The single-page plan export.
 *
 * @react-pdf/renderer does not read Tailwind, so the palette is repeated here
 * as literal hex values. They are the same values as tailwind.config.js and
 * that duplication is deliberate and confined to this one file — the
 * alternative is a runtime that cannot render a PDF at all.
 *
 * Printed on paper this is a light document. That is not a light mode for the
 * app; it is ink on a page, and dark PDFs are unreadable and cost a fortune to
 * print.
 */
const styles = StyleSheet.create({
  page: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 40,
    fontSize: 10,
    color: '#18181B',
    lineHeight: 1.5,
  },
  wordmark: { fontSize: 16, marginBottom: 4, color: '#047857' },
  title: { fontSize: 20, marginBottom: 4 },
  meta: { fontSize: 9, color: '#71717A', marginBottom: 16 },
  summary: { fontSize: 11, marginBottom: 20 },
  action: {
    borderTopWidth: 1,
    borderTopColor: '#E4E4E7',
    paddingTop: 10,
    marginBottom: 10,
  },
  actionTitle: { fontSize: 12, marginBottom: 3 },
  actionBody: { color: '#3F3F46', marginBottom: 4 },
  row: { flexDirection: 'row', gap: 16, marginBottom: 2 },
  label: { fontSize: 9, color: '#71717A' },
  footer: {
    marginTop: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#E4E4E7',
    fontSize: 8,
    color: '#71717A',
  },
})

export function PlanPdf({ plan }: PlanPdfProps) {
  return (
    <Document
      title={`Verge adaptation plan — ${plan.placeName}`}
      author="Verge"
      subject="Climate adaptation plan"
    >
      <Page size="A4" style={styles.page}>
        <Text style={styles.wordmark}>Verge</Text>
        <Text style={styles.title}>Adaptation plan for {plan.placeName}</Text>
        <Text style={styles.meta}>
          Generated {plan.generatedAt} · Dominant risk:{' '}
          {DIMENSION_META[plan.dominantRisk].label}
        </Text>

        <Text style={styles.summary}>{plan.summary}</Text>

        {plan.actions.map((action) => (
          <View key={action.id} style={styles.action} wrap={false}>
            <Text style={styles.actionTitle}>{action.title}</Text>
            <Text style={styles.actionBody}>{action.what}</Text>
            <View style={styles.row}>
              <Text style={styles.label}>
                Estimated cost:{' '}
                {formatCostRange(action.estimatedCostAud.low, action.estimatedCostAud.high)} AUD
              </Text>
              <Text style={styles.label}>Effort: {formatEffort(action.effortHours)}</Text>
              <Text style={styles.label}>Impact: {action.impactScore} of 100</Text>
            </View>
            <Text style={styles.label}>
              Reduces:{' '}
              {action.reduces.map((dimension) => DIMENSION_META[dimension].label).join(', ')}
              {action.renterSafe ? ' · Safe for renters' : ''}
            </Text>
            <Text style={styles.label}>{action.paybackNote}</Text>
          </View>
        ))}

        <Text style={styles.footer}>
          Costs are estimates in Australian dollars, not quotes. Flood figures behind this
          plan are indicative estimates derived from elevation and rainfall history and are
          not a substitute for an official flood map. Climate data from Open-Meteo,
          addresses from OpenStreetMap. Generated by Verge for NextStep Hacks 2026.
        </Text>
      </Page>
    </Document>
  )
}
